### ISSUE TITLE
Fail to build image from dockerfile

### ISSUE THREAD

**Issue by BlueAnthony** [SeanNaren/deepspeech.pytorch#433]
I think that some path of files in Pytorch is different to the Image "pytorch/pytorch:1.0-cuda10.0-cudnn7-devel" mentioned in the dockerfile.
Even I build from source, I still have the same problem. 
Any suggestion?
![Screenshot from 2019-07-02 19-15-48](https://user-images.githubusercontent.com/17959032/60511954-d5ddf000-9d05-11e9-8d6b-92c874abf757.png)

**Comment by SeanNaren** [comment]
Just made a PR that should fix this, I'm going to merge once the build succeeds.

**Comment by BlueAnthony** [comment]
Thank you!!

**Comment by BlueAnthony** [comment]
![image](https://user-images.githubusercontent.com/17959032/60792595-8fbadd80-a198-11e9-8ee4-8c7d5a59b0d9.png)
Although building the image without error, I still cant use it.
Do you know what is this about?

**Comment by SeanNaren** [comment]
What driver have you got installed? It seems like the container requires a driver version higher than the one you've got

**Comment by BlueAnthony** [comment]
![Screenshot from 2019-07-10 15-35-40](https://user-images.githubusercontent.com/17959032/60949816-8bbdc580-a328-11e9-8bc4-d9d65878a0c6.png)
Above picture is about the driver I installed  in real environment
You mean that docker's image will not has its own driver and it still use the same driver as real environment ?

**Comment by SeanNaren** [comment]
Yep it uses whatever local driver you have, but comes with cuda and such. Have you got nvidia-docker2 installed?

**Comment by BlueAnthony** [comment]
Yes, I have already nvidia-docker2.
