### ISSUE TITLE
Loss is 0.000 When using --cuda parameter.

### ISSUE THREAD

**Issue by lintangsutawika** [SeanNaren/deepspeech.pytorch#67]
The loss seems to be always zero when i use `train.py` with `--cuda`
```
Epoch: [1][1/14063]	Time 1.228 (1.228)	Data 0.105 (0.105)	Loss 0.0000 (0.0000)	
Epoch: [1][2/14063]	Time 0.135 (0.681)	Data 0.002 (0.053)	Loss 0.0000 (0.0000)	
Epoch: [1][3/14063]	Time 0.140 (0.501)	Data 0.002 (0.036)	Loss 0.0000 (0.0000)	
Epoch: [1][4/14063]	Time 0.138 (0.410)	Data 0.002 (0.028)	Loss 0.0000 (0.0000)	
Epoch: [1][5/14063]	Time 0.140 (0.356)	Data 0.002 (0.022)	Loss 0.0000 (0.0000)	
Epoch: [1][6/14063]	Time 0.145 (0.321)	Data 0.003 (0.019)	Loss 0.0000 (0.0000)	
Epoch: [1][7/14063]	Time 0.142 (0.295)	Data 0.000 (0.016)	Loss 0.0000 (0.0000)	
Epoch: [1][8/14063]	Time 0.151 (0.277)	Data 0.002 (0.015)	Loss 0.0000 (0.0000)	
Epoch: [1][9/14063]	Time 0.154 (0.264)	Data 0.002 (0.013)	Loss 0.0000 (0.0000)	
Epoch: [1][10/14063]	Time 0.156 (0.253)	Data 0.002 (0.012)	Loss 0.0000 (0.0000)
```
default `train.py` works normally.

```
Epoch: [1][1/14063]	Time 2.203 (2.203)	Data 0.100 (0.100)	Loss 113.9308 (113.9308)	
Epoch: [1][2/14063]	Time 2.132 (2.167)	Data 0.000 (0.050)	Loss 130.0348 (121.9828)	
Epoch: [1][3/14063]	Time 2.235 (2.190)	Data 0.002 (0.034)	Loss 118.3163 (120.7607)	
Epoch: [1][4/14063]	Time 2.307 (2.219)	Data 0.014 (0.029)	Loss 101.6445 (115.9816)	
Epoch: [1][5/14063]	Time 2.482 (2.272)	Data 0.020 (0.027)	Loss 75.0004 (107.7854)	
Epoch: [1][6/14063]	Time 2.604 (2.327)	Data 0.014 (0.025)	Loss 62.9188 (100.3076)
```

What seems to be the problem? Could this be due to my misconfigurations?

**Comment by lintangsutawika** [comment]
It turns out to be wrong configurations. I followed the solution from issue #13, `sudo cmake ..` caused issue when I ran `sudo make`, then I tried `sudo cmake ... -DCUDA_NVCC_FLAGS="-D_FORCE_INLINES" ..`  before `sudo make` again which worked but caused this problem.
I rebuilt warp-ctc with 
```
cmake ..
make
```
now it's working fine.

**Comment by hajix** [comment]
I build the warp_ctc with:

```
mkdir build; cd build
cmake ..
make
```

and install pytorch binding with (issue #112):

```
cd ../pytorch_binding
CUDA_HOME=/usr/local/cuda sudo -E python3 setup.py install
```

but face the same issue! Everything works fine with cpu, but set --cuda flag always gives you zero loss.
@SeanNaren Any Idea about what did I do wrong?

@lintangsutawika can you provide more detail about how you did solve the issue? building without sudo privilege seems is not the proper solution.

**Comment by hajix** [comment]
I build the warp_ctc with:

```
mkdir build; cd build
cmake ..
make
```

and install pytorch binding with (issue #112):

```
cd ../pytorch_binding
CUDA_HOME=/usr/local/cuda sudo -E python3 setup.py install
```

but face the same issue! Everything works fine with cpu, but set --cuda flag always gives you zero loss.
@SeanNaren Any Idea about what did I do wrong?

@lintangsutawika can you provide more detail about how you did solve the issue? building without sudo privilege seems is not the proper solution.

**Comment by SeanNaren** [comment]
Could we see the output once you build the pytorch warp_ctc bindings?

**Comment by hajix** [comment]
`cmake .. `output:

> aj@aj-pc:~/repo/warp-ctc/build$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "9.1", minimum required is "6.5") 
-- cuda found TRUE
-- Found Torch7 in /home/aj/torch/install
-- Torch found /home/aj/torch/install/share/cmake/torch
-- Building shared library with GPU support
-- Building Torch Bindings with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aj/repo/warp-ctc/build

and `make` is as follows:

>[ 10%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is not valid on compute_70 and above, and should be replaced with __shfl_down_sync().To continue using __shfl_down(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::add<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::negate<float, float>, Rop=ctc_helper::add<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(149): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is not valid on compute_70 and above, and should be replaced with __shfl_down_sync().To continue using __shfl_down(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::maximum<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::identity<float, float>, Rop=ctc_helper::maximum<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(157): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::add<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::negate<float, float>, Rop=ctc_helper::add<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(149): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::maximum<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::identity<float, float>, Rop=ctc_helper::maximum<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(157): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::add<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::negate<float, float>, Rop=ctc_helper::add<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(149): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::maximum<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::identity<float, float>, Rop=ctc_helper::maximum<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(157): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::add<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::negate<float, float>, Rop=ctc_helper::add<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(149): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::maximum<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::identity<float, float>, Rop=ctc_helper::maximum<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(157): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::add<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::negate<float, float>, Rop=ctc_helper::add<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(149): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::maximum<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::identity<float, float>, Rop=ctc_helper::maximum<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(157): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::add<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::negate<float, float>, Rop=ctc_helper::add<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(149): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::maximum<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::identity<float, float>, Rop=ctc_helper::maximum<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(157): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::add<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::negate<float, float>, Rop=ctc_helper::add<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(149): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::maximum<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::identity<float, float>, Rop=ctc_helper::maximum<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(157): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::add<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::negate<float, float>, Rop=ctc_helper::add<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::negate<float, float>, Rof=ctc_helper::add<float, float>]" 
(149): here
/home/aj/repo/warp-ctc/src/reduce.cu(44): warning: function "__shfl_down(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(278): here was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
          detected during:
            instantiation of "T CTAReduce<NT, T, Rop>::reduce(int, T, CTAReduce<NT, T, Rop>::Storage &, int, Rop) [with NT=128, T=float, Rop=ctc_helper::maximum<float, float>]" 
(76): here
            instantiation of "void reduce_rows<NT,Iop,Rop,T>(Iop, Rop, const T *, T *, int, int) [with NT=128, Iop=ctc_helper::identity<float, float>, Rop=ctc_helper::maximum<float, float>, T=float]" 
(124): here
            instantiation of "void ReduceHelper::impl(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(139): here
            instantiation of "ctcStatus_t reduce(Iof, Rof, const T *, T *, int, int, __nv_bool, cudaStream_t) [with T=float, Iof=ctc_helper::identity<float, float>, Rof=ctc_helper::maximum<float, float>]" 
(157): here
[ 20%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_ctc_entrypoint.cu.o
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(115): warning: function "__shfl_up(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(261): here was declared deprecated ("__shfl_up() is not valid on compute_70 and above, and should be replaced with __shfl_up_sync().To continue using __shfl_up(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(125): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is not valid on compute_70 and above, and should be replaced with __shfl_up_sync().To continue using __shfl_up(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(126): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is not valid on compute_70 and above, and should be replaced with __shfl_up_sync().To continue using __shfl_up(), specify virtual architecture compute_60 when targeting sm_70 and above, for example, using the pair of compiler options: -arch=compute_60 -code=sm_70.")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(115): warning: function "__shfl_up(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(261): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(125): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(126): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(115): warning: function "__shfl_up(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(261): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(125): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(126): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(115): warning: function "__shfl_up(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(261): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(125): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(126): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(115): warning: function "__shfl_up(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(261): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(125): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(126): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(115): warning: function "__shfl_up(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(261): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(125): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(126): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(115): warning: function "__shfl_up(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(261): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(125): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(126): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(115): warning: function "__shfl_up(float, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(261): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(125): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
/home/aj/repo/warp-ctc/include/contrib/moderngpu/include/device/intrinsics.cuh(126): warning: function "__shfl_up(int, unsigned int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(175): here was declared deprecated ("__shfl_up() is deprecated in favor of __shfl_up_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
Scanning dependencies of target warpctc
[ 30%] Linking CXX shared library libwarpctc.so
[ 30%] Built target warpctc
Scanning dependencies of target test_cpu
[ 40%] Building CXX object CMakeFiles/test_cpu.dir/tests/test_cpu.cpp.o
[ 50%] Linking CXX executable test_cpu
[ 50%] Built target test_cpu
[ 60%] Building NVCC (Device) object CMakeFiles/test_gpu.dir/tests/test_gpu_generated_test_gpu.cu.o
Scanning dependencies of target test_gpu
[ 70%] Linking CXX executable test_gpu
[ 70%] Built target test_gpu
Scanning dependencies of target warp_ctc
[ 80%] Building CXX object CMakeFiles/warp_ctc.dir/torch_binding/binding.cpp.o
[ 90%] Building C object CMakeFiles/warp_ctc.dir/torch_binding/utils.c.o
[100%] Linking CXX shared module libwarp_ctc.so
[100%] Built target warp_ctc

also `sudo make install` is done with no error:

> [ 30%] Built target warpctc
[ 50%] Built target test_cpu
[ 70%] Built target test_gpu
[100%] Built target warp_ctc
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/aj/torch/install/lib/libwarpctc.so
-- Up-to-date: /home/aj/torch/install/include/ctc.h
-- Up-to-date: /home/aj/torch/install/lib/libwarpctc.so
-- Up-to-date: /home/aj/torch/install/../../../../usr/local/lib/libwarp_ctc.so
-- Up-to-date: /home/aj/torch/install/../../../../usr/local/lua/warp_ctc/init.lua

`libwarp_ctc.so`, `libwarpctc.so`, `test_cpu` and `test_gpu` are created in build after compiling warp_ctc.
P.S.: I downgrade gcc and g++ compiler to 4.8.5 due to building problems.

**Comment by hajix** [comment]
hurray... I solved the problem after two days of hard work.

I tried lots of things, so I can not tell exactly what solved the problem. But there are some hints I think are important to solve the issue:

1- gcc and g++ compiler version must be <= 4.9. Compiling warp-ctc with greater versions cause error.

2- I think there are some problems with cuda 9.1. I finally accomplished with cuda 9.0. (but I'm not sure about it)

3-Your fortran version (needed to compile torch) must be the same as g++ and gcc version.

4- Add build folder to `LD_LIBRARY_PATH` and run ./tets_cp and ./test_gpu. It helps to know if the warp-ctc compilation has problem or not.

thanks from @SeanNaren for his attention. Please correct me if I'm wrong.

**Comment by SeanNaren** [comment]
@hajix thanks for posting up solutions, its always been tricky getting warp-ctc installed. I think 1) is crucial. 2) I'm not entirely sure about since I've compiled warp-ctc successfully on CUDA 9.1! Glad your problem is fixed nonetheless

**Comment by voidful** [comment]
warp-ctc likes a endless nightmare
i tried SeanNaren‘s warp-ctc with successful install and pass gpu_test
https://github.com/SeanNaren/warp-ctc
but still getting 0 loss......

Just get get rid of this version
use pytorch official version instead
https://pytorch.org/docs/stable/nn.html#torch.nn.CTCLoss

It works ~

seems that reduction in baidu's version is none ?
